AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/PercentLiteralDelimiters:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/BlockDelimiters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
